name: deepface-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - tensorflow
  - keras
  - opencv
  - scikit-learn
  - matplotlib
  - pip:
      - deepface
